# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupère le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Injecte la vraie clé OpenAI dans script.js
      - name: Inject OpenAI key
        run: |
          sed -i "s|PLACEHOLDER_KEY|${{ secrets.OPENAI_API_KEY }}|g" script.js

      # 3) Configure GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v4

      # 4) Uploade tes fichiers statiques
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

      # 5) Publie sur GitHub Pages (version 2 pour éviter l’ancien upload-artifact v3)
      - name: Publish Pages
        uses: actions/deploy-pages@v2
