# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Injecter la vraie clé OpenAI dans script.js
      - name: Inject OpenAI key
        run: |
          sed -i "s|__OPENAI_API_KEY__|${{ secrets.OPENAI_API_KEY }}|g" script.js

      # 3) Préparer GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v4

      # 4) Uploader tes fichiers statiques (index.html, script.js, etc.)
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

      # 5) Publier sur la branche gh-pages
      - name: Publish Pages
        uses: actions/deploy-pages@v1
